/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Homework_database_add.java
 *
 * Created on Nov 10, 2011, 8:43:42 PM
 */
package timetable;

import java.awt.Color;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.RandomAccessFile;
import javax.swing.*;

/**
 *
 * @author Abhi
 */
public class administration extends javax.swing.JFrame {
    
   static int n1 =0;
   static int n2 =0;
   static int n3 =0;
    private static final long serialVersionUID = 1L;
    
        public static void main(String args[]) {
        
        List_Homework_database MList = new List_Homework_database();
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(administration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(administration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(administration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(administration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new administration().setVisible(true);
            }
        });
    }
        
            public static void unorremove(int ifdeleteornot)
    {
        int raflength;
   
         try {

RandomAccessFile raf = new RandomAccessFile(Homework_datetimecheck.memberurl, "rw");
    

raflength =   (((int) raf.length())/167);

Member_details default1 = Member_details_array.getMembers()[n2];

raf.skipBytes((n2)*167);
// starts writing
                raf.write(default1.getUserID());
                raf.writeUTF(default1.getUsername());
                raf.writeUTF(default1.getPassword());
                raf.writeUTF(default1.getSubject1());
                raf.writeUTF(default1.getSubject2());
                raf.writeUTF(default1.getSubject3());
                raf.writeUTF(default1.getSubject4());
                raf.writeUTF(default1.getSubject5());
                raf.writeUTF(default1.getSubject6());
                raf.writeUTF(default1.getSubject7());
                raf.write(1);
                
                System.out.print(raf.length());
                
   System.out.print(Timetable_main_RWRAF.checkDelete());           
                 JOptionPane.showMessageDialog(null,"Account Deleted!", "Timetable Management Program", JOptionPane.INFORMATION_MESSAGE);
                 
                 
               
    
} catch (FileNotFoundException e) {
        e.printStackTrace();
} catch (IOException e) {
        e.printStackTrace();
}
    }

    /** Creates new form Homework_database_add */
    public administration() {
        initComponents();
        
        jTabbedPane1.setBackground(login_area.FINAL_BG_COLOR);
        jPanel1.setBackground(login_area.FINAL_BG_COLOR);
     Member_details_add.readarray();
    
    Member_details default1 = Member_details_array.getMembers()[0];
        
   
    // Username
    
 DescField37.setText(default1.getUsername());// TODO add your handling code here:

 
    // Subject 1
 
     DescField32.setText(default1.getSubject1());
    
     // Subject 2
     
     DescField35.setText(default1.getSubject2());
     
     DescField36.setText(default1.getSubject3());
     
     DescField31.setText(default1.getSubject4());
     
     DescField33.setText(default1.getSubject5());
     
     DescField30.setText(default1.getSubject6());
     
     DescField34.setText(default1.getSubject7());
        
    }
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        DescField30 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jButton26 = new javax.swing.JButton();
        DescField31 = new javax.swing.JTextField();
        DescField32 = new javax.swing.JTextField();
        DescField33 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jButton28 = new javax.swing.JButton();
        DescField34 = new javax.swing.JTextField();
        DescField35 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        DescField36 = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        DescField37 = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        DescField38 = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        DescField51 = new javax.swing.JTextField();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        DescField55 = new javax.swing.JTextField();
        jLabel60 = new javax.swing.JLabel();
        DescField57 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();
        jComboBox4 = new javax.swing.JComboBox();
        jComboBox5 = new javax.swing.JComboBox();
        jComboBox6 = new javax.swing.JComboBox();
        jComboBox7 = new javax.swing.JComboBox();
        jComboBox8 = new javax.swing.JComboBox();
        jPanel4 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jLabel61 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setLocation(new java.awt.Point(343, 50));

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/timetable/header.png"))); // NOI18N
        jLabel3.setMinimumSize(new java.awt.Dimension(490, 235));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 460, 50));

        jLabel6.setText("Return");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 430, -1, -1));

        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        DescField30.setEditable(false);

        jLabel33.setText("Group 5 Subject:");

        jButton26.setText("<");
        jButton26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton26MouseClicked(evt);
            }
        });

        DescField31.setEditable(false);

        DescField32.setEditable(false);

        DescField33.setEditable(false);

        jLabel34.setText("Group 6 Subject:");

        jButton28.setText(">");
        jButton28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton28MouseClicked(evt);
            }
        });

        DescField34.setEditable(false);

        DescField35.setEditable(false);

        jLabel35.setText("Username:");

        DescField36.setEditable(false);

        jLabel36.setText("Group 1 Subject:");

        jLabel37.setText("7th Subject:");

        DescField37.setEditable(false);

        jLabel38.setText("Group 3 Subject:");

        jLabel39.setText("Group 4 Subject:");

        jLabel40.setText("Group 2 Subject:");

        DescField38.setEditable(false);
        DescField38.setText("<hidden>");

        jLabel41.setText("Password:");

        org.jdesktop.layout.GroupLayout jPanel6Layout = new org.jdesktop.layout.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(jLabel35)
                        .add(jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, DescField37)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel41)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, DescField38, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 110, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jButton26, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(jButton28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(27, 27, 27)
                .add(jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel6Layout.createSequentialGroup()
                        .add(jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel36)
                            .add(DescField32, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                            .add(jLabel40)
                            .add(DescField35, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                            .add(jLabel38)
                            .add(DescField36, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(DescField30, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                            .add(jLabel39)
                            .add(jLabel33)
                            .add(jLabel34)
                            .add(DescField33, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, DescField31, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)))
                    .add(jLabel37)
                    .add(DescField34, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE))
                .add(47, 47, 47))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel6Layout.createSequentialGroup()
                        .add(jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel39)
                            .add(jLabel36))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(DescField31, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(DescField32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel33)
                            .add(jLabel40))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(DescField33, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(DescField35, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(8, 8, 8)
                        .add(jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel34)
                            .add(jLabel38))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(DescField30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(DescField36, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel37)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(DescField34, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanel6Layout.createSequentialGroup()
                        .add(jLabel35)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(DescField37, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel41)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(DescField38, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButton26)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButton28)))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("View Users", jPanel6);

        jButton2.setText("Add User");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jLabel51.setText("Group 1 Subject:");

        jLabel52.setText("Username:");

        jLabel53.setText("Group 5 Subject:");

        jLabel54.setText("Group 3 Subject:");

        jLabel55.setText("Group 6 Subject:");

        jLabel56.setText("Group 4 Subject:");

        jLabel57.setText("7th Subject (Optional):");

        jLabel58.setText("4 Digit Code:");

        jLabel59.setText("Group 2 Subject:");

        jLabel60.setText("Re-type Code:");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Afrikaans", "Albanian", "Amharic", "Arabic", "Belarusian", "Bengali", "Bosnian", "Bulgarian", "Burmese", "Catalan", "Chichewa", "Chinese", "Croatian", "Czech", "Danish", "Dhivehi", "Dutch", "Dzongkha", "English", "Estonian", "Finnish", "French", "Georgian", "German", "Greek", "Gujarati", "Hebrew", "Hindi", "Hungarian", "Icelandic", "Indonesian", "Italian", "Japanese", "Kannada", "Korean", "Latvian", "Lithuanian", "Macedonian", "Malay", "Marathi", "Mongolian", "Nepali", "Norwegian", "Persian", "Polish", "Portuguese", "Romanian", "Russian", "Serbian", "Sesotho", "Shona", "Sinhala", "Slovene", "Spanish", "Swahili", "Swati", "Swedish", "Tamil", "Telugu", "Thai", "Tibetan", "Tigrigna", "Tswana", "Turkish", "Ukrainian", "Urdu", "Uzbek", "Vietnamese", "Welsh", "Yorùbá" }));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Afrikaans", "Albanian", "Amharic", "Arabic", "Belarusian", "Bengali", "Bosnian", "Bulgarian", "Burmese", "Catalan", "Chichewa", "Chinese", "Croatian", "Czech", "Danish", "Dhivehi", "Dutch", "Dzongkha", "English", "Estonian", "Finnish", "French", "Georgian", "German", "Greek", "Gujarati", "Hebrew", "Hindi", "Hungarian", "Icelandic", "Indonesian", "Italian", "Japanese", "Kannada", "Korean", "Latvian", "Lithuanian", "Macedonian", "Malay", "Marathi", "Mongolian", "Nepali", "Norwegian", "Persian", "Polish", "Portuguese", "Romanian", "Russian", "Serbian", "Sesotho", "Shona", "Sinhala", "Slovene", "Spanish", "Swahili", "Swati", "Swedish", "Tamil", "Telugu", "Thai", "Tibetan", "Tigrigna", "Tswana", "Turkish", "Ukrainian", "Urdu", "Uzbek", "Vietnamese", "Welsh", "Yorùbá" }));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "History", "Economics", "Psychology", "Philosophy", "ITGS", "Geography" }));

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Physics", "Chemistry", "Biology", "Design Technology", "Environmental systems and societies" }));

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Math Studies", "Mathematics", "Computer Science" }));

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Music", "Theater", "Visual Arts", "Film" }));

        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Further Mathematics", "Further Dutch", "None" }));

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel3Layout.createSequentialGroup()
                        .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel52)
                            .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                                .add(org.jdesktop.layout.GroupLayout.LEADING, DescField51)
                                .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel58)
                                .add(org.jdesktop.layout.GroupLayout.LEADING, DescField55, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 110, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(DescField57, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 110, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel60))
                        .add(27, 27, 27)
                        .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel51)
                            .add(jLabel59)
                            .add(jLabel54)
                            .add(jComboBox2, 0, 120, Short.MAX_VALUE)
                            .add(jComboBox3, 0, 120, Short.MAX_VALUE)
                            .add(jComboBox4, 0, 126, Short.MAX_VALUE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel3Layout.createSequentialGroup()
                        .add(jButton2)
                        .add(15, 15, 15)))
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel56)
                    .add(jLabel53)
                    .add(jLabel55)
                    .add(jLabel57, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                    .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, jComboBox7, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, jComboBox6, 0, 1, Short.MAX_VALUE)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, jComboBox5, 0, 131, Short.MAX_VALUE))
                    .add(jComboBox8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 129, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(36, 36, 36))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel52)
                    .add(jLabel56)
                    .add(jLabel51))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(DescField51, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jComboBox2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jComboBox5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel58)
                    .add(jLabel53)
                    .add(jLabel59))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(DescField55, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jComboBox3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jComboBox6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(8, 8, 8)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel55)
                    .add(jLabel54)
                    .add(jLabel60))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(DescField57, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jComboBox4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jComboBox7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jPanel3Layout.createSequentialGroup()
                        .add(jLabel57)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jComboBox8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(50, Short.MAX_VALUE))
                    .add(jPanel3Layout.createSequentialGroup()
                        .add(jButton2)
                        .addContainerGap())))
        );

        jTabbedPane1.addTab("Add User", jPanel3);

        jButton3.setText("Save");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jLabel61.setText("Study Start Time:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "8:00", "8:15", "8:30", "8:45", "9:00", "9:15", "9:30", "9:45", "10:00", "10:15", "10:30", "10:45", "11:00", "11:15", "11:30", "11:45", "12:00", "12:15", "12:30", "12:45", "13:00", "13:15", "13:30", "13:45", "14:00", "14:15", "14:30", "14:45", "15:00", "15:15", "15:30", "15:45", "16:00", "16:15", "16:30", "16:45", "17:00", "17:15", "17:30", "17:45", "18:00", "18:15", "18:30", "18:45", "19:00", "19:15", "19:30", "19:45", "20:00" }));

        org.jdesktop.layout.GroupLayout jPanel4Layout = new org.jdesktop.layout.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel4Layout.createSequentialGroup()
                        .add(146, 146, 146)
                        .add(jComboBox1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 153, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanel4Layout.createSequentialGroup()
                        .add(186, 186, 186)
                        .add(jButton3))
                    .add(jPanel4Layout.createSequentialGroup()
                        .add(163, 163, 163)
                        .add(jLabel61)))
                .addContainerGap(160, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .add(57, 57, 57)
                .add(jLabel61)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jComboBox1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jButton3)
                .addContainerGap(131, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Settings", jPanel4);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 480, 330));
        jTabbedPane1.getAccessibleContext().setAccessibleName("Add User");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
    this.setVisible(false);// TODO add your handling code here:
    
     login_area.open1 = 0;
}//GEN-LAST:event_jLabel6MouseClicked

private void jButton28MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton28MouseClicked
    
    Member_details Userfile = Member_details_array.getMembers()[n3];
    
    if(Member_details_add.getLength()-1 > n3)
        
    {
        n3 += 1;
    Member_details_add.readarray();
    
    Member_details default1 = Member_details_array.getMembers()[n3];
        
    
     DescField37.setText(default1.getUsername());// TODO add your handling code here:
  
     DescField32.setText(default1.getSubject1());
     DescField35.setText(default1.getSubject2());
     DescField36.setText(default1.getSubject3());
     DescField31.setText(default1.getSubject4());
     DescField33.setText(default1.getSubject5());
     DescField30.setText(default1.getSubject6());
     DescField34.setText(default1.getSubject7());       
        
    }
    else
    {
        
    }
}//GEN-LAST:event_jButton28MouseClicked

private void jButton26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton26MouseClicked
    Member_details Userfile = Member_details_array.getMembers()[n3];
    
    if(n3>0)
        
    {
        n3 -= 1;
    Member_details_add.readarray();
    
    Member_details default1 = Member_details_array.getMembers()[n3];
        
    
     DescField37.setText(default1.getUsername());// TODO add your handling code here:
   
     DescField32.setText(default1.getSubject1());
     DescField35.setText(default1.getSubject2());
     DescField36.setText(default1.getSubject3());
     DescField31.setText(default1.getSubject4());
     DescField33.setText(default1.getSubject5());
     DescField30.setText(default1.getSubject6());
     DescField34.setText(default1.getSubject7());
     
        
    }
    else
    {
        
    }
}//GEN-LAST:event_jButton26MouseClicked

private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked

  String usernameadd = DescField51.getText();
  String passwordadd = DescField55.getText();
  String subject1 = (String)jComboBox2.getSelectedItem();
  String subject2 = (String)jComboBox3.getSelectedItem();
  String subject3 = (String)jComboBox4.getSelectedItem();
  String subject4 = (String)jComboBox5.getSelectedItem();
  String subject5 = (String)jComboBox6.getSelectedItem();
  String subject6 = (String)jComboBox7.getSelectedItem();
  String subject7 = (String)jComboBox8.getSelectedItem();
  int delete = 0;
    
  if(passwordadd.equals(DescField57.getText()))
  {

  if(passwordadd.length() > 4 && passwordadd.length() < 4)
    {        
                 JOptionPane.showMessageDialog(null,"Please enter a four digit pin and try again!", "Timetable Management Program", JOptionPane.INFORMATION_MESSAGE);
    
    }
    else{
    Member_details_add.addtoarray(usernameadd, passwordadd, subject1, subject2, subject3, subject4, subject5, subject6, subject7, delete);
     JOptionPane.showMessageDialog(null,"User Added!", "Timetable Management Program", JOptionPane.INFORMATION_MESSAGE);
        this.setVisible(false);
        login_area.open1 = 0;
    }
  }
  else
  {
       JOptionPane.showMessageDialog(null,"The two passcodes don't match try again!", "Timetable Management Program", JOptionPane.INFORMATION_MESSAGE);
  }
    
}//GEN-LAST:event_jButton2MouseClicked

private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
 readsettings.write((String)jComboBox1.getSelectedItem());
      JOptionPane.showMessageDialog(null,"Settings changed!", "Timetable Management Program", JOptionPane.INFORMATION_MESSAGE);
       login_area.open1 = 0;
        this.setVisible(false);
}//GEN-LAST:event_jButton3MouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DescField30;
    private javax.swing.JTextField DescField31;
    private javax.swing.JTextField DescField32;
    private javax.swing.JTextField DescField33;
    private javax.swing.JTextField DescField34;
    private javax.swing.JTextField DescField35;
    private javax.swing.JTextField DescField36;
    private javax.swing.JTextField DescField37;
    private javax.swing.JTextField DescField38;
    private javax.swing.JTextField DescField51;
    private javax.swing.JTextField DescField55;
    private javax.swing.JTextField DescField57;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JComboBox jComboBox6;
    private javax.swing.JComboBox jComboBox7;
    private javax.swing.JComboBox jComboBox8;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
