/**
 *
 * @author Abhi Agarwal
 * Timetable Management System
 * Abhi Agarwal, 30th January 2012
 * Bangkok Patana School
 * 
 * Mac Book Pro 10.7, 2.66 GHz Intel Core i7, 4GB 1067 MHz DDR3
 * The function class to search records
 * Integrated Development Environment Netbeans 7.0.1
 * 
 */
package timetable;

import javax.swing.table.*;

/**
 *
 * @author Abhi
 */
public class Homework_database_search extends javax.swing.JFrame {
    private static final long serialVersionUID = 1L;
         
    
    private int n = 0;
  private int n1 = 0;
  private int n2 = 0;
  private int n3 = 0; 
    private int n4 = 0;  
    /** Creates new form Homework_database_viewsearch */
    public Homework_database_search() {
        initComponents();
        jPanel3.setBackground(login_area.FINAL_BG_COLOR);
        
        this.setDefaultCloseOperation(0);

        
                Timetable_main_RWRAF.read(0);
String subjecttoput = "";
String desctoput = "";
String difftoput = "";
int timetoput = 0;
         
for(int i=0; i<=Timetable_main_RWRAF.getLength(); i++)
{
    Timetable_main_RWRAF.read(i);
    
    
 if (Timetable_main_RWRAF.checkDelete() == 0)
 {
            
subjecttoput = Timetable_main_RWRAF.getSubject();
           
desctoput = Timetable_main_RWRAF.getDesc();
           
difftoput = Timetable_main_RWRAF.getDiff();

timetoput = Timetable_main_RWRAF.getTime();

 jTable1.getModel().setValueAt(subjecttoput.trim(), n, 0);
  jTable1.getModel().setValueAt(desctoput.trim(), n, 1);
   jTable1.getModel().setValueAt(difftoput.trim(), n, 2);
    jTable1.getModel().setValueAt(timetoput, n, 3);
    if(subjecttoput != null)
{
    n+=1;
   
}

 }
 
}
        
    }
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(343, 50));

        jPanel3.setBackground(new java.awt.Color(255, 102, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/timetable/header.png"))); // NOI18N
        jLabel7.setMinimumSize(new java.awt.Dimension(490, 235));
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 510, 50));

        jLabel12.setText("Return");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 460, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Subjects", "Description", "Time", "Difficulty" }));
        jPanel3.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, 30));

        jLabel1.setText("Search:");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, -1, -1));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });
        jPanel3.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 160, -1));

        jLabel2.setText("Search in:");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Subject", "Description", "Difficulty", "Time Taken"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getColumn(0).setResizable(false);
        jTable1.getColumnModel().getColumn(1).setResizable(false);
        jTable1.getColumnModel().getColumn(2).setResizable(false);
        jTable1.getColumnModel().getColumn(3).setResizable(false);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 510, 230));

        jLabel6.setText("Return");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 370, -1, -1));

        jButton2.setText("Reset");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, -1, -1));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 529, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 397, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
    this.setVisible(false);// TODO add your handling code here:
     login_area.open1 = 0;
}//GEN-LAST:event_jLabel12MouseClicked

private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
    this.setVisible(false);
    
    login_area.open1 = 0;
}//GEN-LAST:event_jLabel6MouseClicked

private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
Timetable_main_RWRAF.read(0);
String subjecttoput = "";
String desctoput = "";
String difftoput = "";
int timetoput = 0;
         
DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
model.setRowCount(0);
n=0;
model.setRowCount(12);
for(int i=0; i<=Timetable_main_RWRAF.getLength(); i++)
{
    Timetable_main_RWRAF.read(i);
    
    
 if (Timetable_main_RWRAF.checkDelete() == 0)
 {
            
subjecttoput = Timetable_main_RWRAF.getSubject();
           
desctoput = Timetable_main_RWRAF.getDesc();
           
difftoput = Timetable_main_RWRAF.getDiff();

timetoput = Timetable_main_RWRAF.getTime();

 jTable1.getModel().setValueAt(subjecttoput.trim(), n, 0);
  jTable1.getModel().setValueAt(desctoput.trim(), n, 1);
   jTable1.getModel().setValueAt(difftoput.trim(), n, 2);
    jTable1.getModel().setValueAt(timetoput, n, 3);
    if(subjecttoput != null)
{
    n+=1;
}

 }
 
}
        
    
    
}//GEN-LAST:event_jButton2MouseClicked

private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed

}//GEN-LAST:event_jTextField1ActionPerformed

private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
   
    // Clears Table
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
     model.setRowCount(0);
     model.setRowCount(12);
  String subject = "";
  int ID = 0;
  String desc = "";
  String diff = "";
  int time = 0;
     
     if(jComboBox1.getSelectedIndex() == 0)
     {
         n1=0;
     model.setRowCount(0);
     model.setRowCount(12);
         
        for(int i=0; i<=Timetable_main_RWRAF.getLength(); i++)
{
    Timetable_main_RWRAF.read(i);
 if (Timetable_main_RWRAF.checkDelete() == 0)
 {
ID = Timetable_main_RWRAF.getID();
            
subject = Timetable_main_RWRAF.getSubject().trim();
           
desc = Timetable_main_RWRAF.getDesc().trim();
           
diff = Timetable_main_RWRAF.getDiff().trim();

time = Timetable_main_RWRAF.getTime();

boolean trueornot = subject.toLowerCase().contains(jTextField1.getText().trim().toLowerCase());



    if(trueornot == true)
    {
        
        
      jTable1.getModel().setValueAt(subject, n1, 0);
  jTable1.getModel().setValueAt(desc, n1, 1);
   jTable1.getModel().setValueAt(diff, n1, 2);
    jTable1.getModel().setValueAt(time, n1, 3);   
    n1+=1;
    }
 } 
     }
     
     }
     
     
          if(jComboBox1.getSelectedIndex() == 1)
     {
          model.setRowCount(0);
     model.setRowCount(12);
     n2=0;
     
        for(int i=0; i<=Timetable_main_RWRAF.getLength(); i++)
{
    Timetable_main_RWRAF.read(i);
 if (Timetable_main_RWRAF.checkDelete() == 0)
 {
ID = Timetable_main_RWRAF.getID();
            
subject = Timetable_main_RWRAF.getSubject().trim();
           
desc = Timetable_main_RWRAF.getDesc().trim();
           
diff = Timetable_main_RWRAF.getDiff().trim();

time = Timetable_main_RWRAF.getTime();
boolean trueornot = desc.toLowerCase().contains(jTextField1.getText().trim().toLowerCase());


    if(trueornot == true)
    {
      jTable1.getModel().setValueAt(subject, n2, 0);
  jTable1.getModel().setValueAt(desc, n2, 1);
   jTable1.getModel().setValueAt(diff, n2, 2);
    jTable1.getModel().setValueAt(time, n2, 3);   
    n2+=1;
    }
 } 
     }
     
     }
          if(jComboBox1.getSelectedIndex() == 2)
     {
          model.setRowCount(0);
     model.setRowCount(12);
     n4=0;
     
        for(int i=0; i<=Timetable_main_RWRAF.getLength(); i++)
{
    Timetable_main_RWRAF.read(i);
 if (Timetable_main_RWRAF.checkDelete() == 0)
 {
ID = Timetable_main_RWRAF.getID();
            
subject = Timetable_main_RWRAF.getSubject().trim();
           
desc = Timetable_main_RWRAF.getDesc().trim();
           
diff = Timetable_main_RWRAF.getDiff().trim();

time = Timetable_main_RWRAF.getTime();

String time2 = Integer.toString(time);
boolean trueornot = time2.toLowerCase().contains(jTextField1.getText().trim().toLowerCase());


    if(trueornot == true)
    {
      jTable1.getModel().setValueAt(subject, n4, 0);
  jTable1.getModel().setValueAt(desc, n4, 1);
   jTable1.getModel().setValueAt(diff, n4, 2);
    jTable1.getModel().setValueAt(time, n4, 3);   
    n4+=1;
    }
 } 
     }
     
     }
          
          if(jComboBox1.getSelectedIndex() == 3)
     {
          model.setRowCount(0);
     model.setRowCount(12);
     n3=0;
     
        for(int i=0; i<=Timetable_main_RWRAF.getLength(); i++)
{
    Timetable_main_RWRAF.read(i);
 if (Timetable_main_RWRAF.checkDelete() == 0)
 {
ID = Timetable_main_RWRAF.getID();
            
subject = Timetable_main_RWRAF.getSubject().trim();
           
desc = Timetable_main_RWRAF.getDesc().trim();
           
diff = Timetable_main_RWRAF.getDiff().trim();

time = Timetable_main_RWRAF.getTime();
boolean trueornot = diff.toLowerCase().contains(jTextField1.getText().trim().toLowerCase());


    if(trueornot == true)
    {
      jTable1.getModel().setValueAt(subject, n3, 0);
  jTable1.getModel().setValueAt(desc, n3, 1);
   jTable1.getModel().setValueAt(diff, n3, 2);
    jTable1.getModel().setValueAt(time, n3, 3);   
    n3+=1;
    }
 } 
     }
     
     }
}//GEN-LAST:event_jTextField1KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Homework_database_search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Homework_database_search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Homework_database_search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Homework_database_search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Homework_database_search().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables


}