/**
 *
 * @author Abhi Agarwal
 * Timetable Management System
 * Abhi Agarwal, 30th January 2012
 * Bangkok Patana School
 * 
 * Mac Book Pro 10.7, 2.66 GHz Intel Core i7, 4GB 1067 MHz DDR3
 * Adding a record to the Linked List and RAF
 * Integrated Development Environment Netbeans 7.0.1
 * 
 */
package timetable;

import javax.swing.*;

/**
 *
 * @author Abhi
 */
public class Homework_database_add extends javax.swing.JFrame {
    
        public static void main(String args[]) {
        
        List_Homework_database MList = new List_Homework_database();
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Homework_database_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Homework_database_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Homework_database_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Homework_database_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Homework_database_add().setVisible(true);
            }
        });
    }

    /** Creates new form Homework_database_add */
    public Homework_database_add() {
        initComponents();

         Member_details_add.readarray();    
         Member_details default1 = Member_details_array.getMembers()[Member_loggedin.getNumber()];
         
         Subject.removeAllItems();
         Subject.insertItemAt(default1.getSubject1(), 0);
         Subject.insertItemAt(default1.getSubject2(), 1);
         Subject.insertItemAt(default1.getSubject3(), 2);
         Subject.insertItemAt(default1.getSubject4(), 3);
         Subject.insertItemAt(default1.getSubject5(), 4);
         Subject.insertItemAt(default1.getSubject6(), 5);
         if(default1.getSubject7().equals("None"))
         {
             
         }
         else
         {
         Subject.insertItemAt(default1.getSubject7(), 0);
         }
        
        this.setDefaultCloseOperation(0);
        jPanel1.setBackground(login_area.FINAL_BG_COLOR);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Timef1 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Subject = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        DescField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        DiffField1 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(343, 50));

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/timetable/header.png"))); // NOI18N
        jLabel3.setMinimumSize(new java.awt.Dimension(490, 235));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 460, 50));

        jLabel1.setText("Difficulty: \u0000");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, -1, -1));

        Timef1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "15", "30", "45", "60", "75", "90", "105", "120", "135", "150", "165", "180" }));
        jPanel1.add(Timef1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 150, -1));

        jLabel2.setText("Subjects:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, -1, -1));

        jLabel4.setText("Description of homework: ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, -1, -1));

        Subject.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Computer Science", "Physics", "Mathematics", "English", "French", "Further Mathematics", "Economics" }));
        jPanel1.add(Subject, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 150, -1));

        jLabel5.setText("Task Time (minutes): \u0000");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, -1, -1));

        DescField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DescFieldActionPerformed(evt);
            }
        });
        jPanel1.add(DescField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 100, -1));

        jButton1.setText("ADD");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 100, -1));

        jLabel6.setText("Return");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 330, -1, -1));

        DiffField1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Easy", "Medium", "Hard" }));
        jPanel1.add(DiffField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 100, -1));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void DescFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DescFieldActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_DescFieldActionPerformed

private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
    this.setVisible(false);
    
    login_area.open1 = 0;
}//GEN-LAST:event_jLabel6MouseClicked

private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
  
  String subjectchosen = (String)Subject.getSelectedItem();
  String descchosen = DescField.getText();
  String diffchosen = (String)DiffField1.getSelectedItem();
  String timechosenstring = (String)Timef1.getSelectedItem();
  if(descchosen.length() < 501)
  {
  
  int timechoseninteger = Integer.parseInt(timechosenstring);
  
    
Homework_database homework = new Homework_database(subjectchosen, descchosen, diffchosen, timechoseninteger);
List_Homework_database List = new List_Homework_database();
int size = List.size();
List.add(homework, size+1);
Timetable_main_RWRAF.write(homework);


 JOptionPane.showMessageDialog(null,"Homework added!", "Timetable Management Program", JOptionPane.INFORMATION_MESSAGE);
 login_area.open1 = 0;
        this.setVisible(false);
  }
  else
  {
       JOptionPane.showMessageDialog(null,"Your description is too big, please cut it to 500 words.", "Timetable Management Program", JOptionPane.INFORMATION_MESSAGE);

  }
        
}//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DescField;
    private javax.swing.JComboBox DiffField1;
    private javax.swing.JComboBox Subject;
    private javax.swing.JComboBox Timef1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
