/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Stimulated_timetable_database_simulate.java
 *
 * Created on Nov 10, 2011, 10:16:29 PM
 */
package timetable;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Abhi
 */
public final class Stimulated_timetable_database_simulate extends javax.swing.JFrame {
    private static final long serialVersionUID = 1L;

    /** Creates new form Stimulated_timetable_database_simulate */
    public Stimulated_timetable_database_simulate() throws InterruptedException {
        initComponents();
        jPanel1.setBackground(login_area.FINAL_BG_COLOR);
                  this.repaint();
    jProgressBar1.setValue(100);
    jProgressBar1.repaint();
          this.repaint();
        
    }
public void pbar() throws InterruptedException{
        this.repaint();
    jProgressBar1.setValue(10);
    jProgressBar1.repaint();
    jLabel1.setText("10%");
      Thread.sleep(1000);  
          this.repaint();

    jProgressBar1.setValue(20);
    jProgressBar1.repaint();
    jLabel1.setText("20%");
    
        jProgressBar1.setValue(30);
    jProgressBar1.repaint();
    jLabel1.setText("30%");
    
        jProgressBar1.setValue(40);
    jProgressBar1.repaint();
    jLabel1.setText("40%");
    
        jProgressBar1.setValue(50);
    jProgressBar1.repaint();
    jLabel1.setText("50%");



}
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(100, 200, 0, 0));
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Press enter to continue");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 72, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
   
    this.repaint();
    jProgressBar1.setValue(100);
    jProgressBar1.repaint();
    jLabel1.setText("Loaded");
    
    new SimulatedTimeable().setVisible(true);
    this.dispose();
    
}//GEN-LAST:event_formKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Stimulated_timetable_database_simulate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Stimulated_timetable_database_simulate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Stimulated_timetable_database_simulate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Stimulated_timetable_database_simulate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                try {
                    new Stimulated_timetable_database_simulate().setVisible(true);
                    
                    
                } catch (InterruptedException ex) {
                    Logger.getLogger(Stimulated_timetable_database_simulate.class.getName()).log(Level.SEVERE, null, ex);
                }
                
              
            }
            
        });
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
}
